export const SET_CARDLIST = "SET_CARDLIST";
export const SET_CARDLIST_LOADING = "SET_CARDLIST_LOADING";
export const SET_CARDLIST_ERROR = "SET_CARDLIST_ERROR";
export const SET_CARDLIST_BY_CURRENT_SORT = "SET_CARDLIST_BY_CURRENT_SORT";